language: node_js
sudo: required
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
node_js:
  - "10"
  - "12"
  - "node"
addons:
  apt:
    packages:
      # Required by Electron
      # https://github.com/juliangruber/electron-stream#travis
      - xvfb
      # Required by Chrome >42
      # https://github.com/electron/electron/issues/1518#issuecomment-97708181
      - libgconf-2-4
install:
  # Required by Electron
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm i -g npm
  - npm ci
before_script:
  # Building sources
  - npm run build
stages:
  - lint
  - test
  - release
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: test
      script: npm run test
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
